<?php
/**
 * PHP syntax code validation script
 * 
 * Validates code generated by JavaScriptTranslator.
 * Code is saved in file named "%code%". This script loads the file and tries
 * to initialize an anonymous function. If the code is invalid, it throws
 * Fatal error and ends. Otherwise it returns "ok" value.
 */
if (!isset($_GET['code']) || !$_GET['code'])
  die('error');

require __DIR__ . '/../libs/autoload.php';
require __DIR__ . '/../app/lib/JavaScriptTranslator/PHPValidator.php';

$validator = new \ITILSimulator\Base\JavaScriptTranslator\PHPValidator(null);
echo $validator->verify($_GET['code']);
$validator->clear($_GET['code']);