<?php

namespace Proxies\__CG__\ITILSimulator\Entities\Training;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Service extends \ITILSimulator\Entities\Training\Service implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addConfigurationItem(\ITILSimulator\Entities\Training\ConfigurationItem $ci)
    {
        $this->__load();
        return parent::addConfigurationItem($ci);
    }

    public function removeConfigurationItem(\ITILSimulator\Entities\Training\ConfigurationItem $ci)
    {
        $this->__load();
        return parent::removeConfigurationItem($ci);
    }

    public function getDefaultSpecification()
    {
        $this->__load();
        return parent::getDefaultSpecification();
    }

    public function getTrainingId()
    {
        $this->__load();
        return parent::getTrainingId();
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setGraphicDesignData($graphicDesignData)
    {
        $this->__load();
        return parent::setGraphicDesignData($graphicDesignData);
    }

    public function getGraphicDesignData()
    {
        $this->__load();
        return parent::getGraphicDesignData();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setServiceOwner($serviceOwner)
    {
        $this->__load();
        return parent::setServiceOwner($serviceOwner);
    }

    public function getServiceOwner()
    {
        $this->__load();
        return parent::getServiceOwner();
    }

    public function setTraining($training)
    {
        $this->__load();
        return parent::setTraining($training);
    }

    public function getTraining()
    {
        $this->__load();
        return parent::getTraining();
    }

    public function getConfigurationItems()
    {
        $this->__load();
        return parent::getConfigurationItems();
    }

    public function getServiceSpecifications()
    {
        $this->__load();
        return parent::getServiceSpecifications();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function __call($name, $args)
    {
        $this->__load();
        return parent::__call($name, $args);
    }

    public function &__get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        $this->__load();
        return parent::__unset($name);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'code', 'description', 'serviceOwner', 'graphicDesignData', 'training', 'configurationItems', 'serviceSpecifications');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}