<?php

namespace Proxies\__CG__\ITILSimulator\Entities\Session;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TrainingStep extends \ITILSimulator\Entities\Session\TrainingStep implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getLastValidScenarioStep()
    {
        $this->__load();
        return parent::getLastValidScenarioStep();
    }

    public function getScenarioId()
    {
        $this->__load();
        return parent::getScenarioId();
    }

    public function getTrainingId()
    {
        $this->__load();
        return parent::getTrainingId();
    }

    public function finish()
    {
        $this->__load();
        return parent::finish();
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function getTraining()
    {
        $this->__load();
        return parent::getTraining();
    }

    public function isDesign()
    {
        $this->__load();
        return parent::isDesign();
    }

    public function isAvailableForUser($user)
    {
        $this->__load();
        return parent::isAvailableForUser($user);
    }

    public function getSessionId()
    {
        $this->__load();
        return parent::getSessionId();
    }

    public function setDateEnd($dateEnd)
    {
        $this->__load();
        return parent::setDateEnd($dateEnd);
    }

    public function getDateEnd()
    {
        $this->__load();
        return parent::getDateEnd();
    }

    public function setDateStart($dateStart)
    {
        $this->__load();
        return parent::setDateStart($dateStart);
    }

    public function getDateStart()
    {
        $this->__load();
        return parent::getDateStart();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getScenario()
    {
        $this->__load();
        return parent::getScenario();
    }

    public function getSession()
    {
        $this->__load();
        return parent::getSession();
    }

    public function setScenario($scenario)
    {
        $this->__load();
        return parent::setScenario($scenario);
    }

    public function setSession($session)
    {
        $this->__load();
        return parent::setSession($session);
    }

    public function getIsFinished()
    {
        $this->__load();
        return parent::getIsFinished();
    }

    public function isFinished()
    {
        $this->__load();
        return parent::isFinished();
    }

    public function getScenarioSteps()
    {
        $this->__load();
        return parent::getScenarioSteps();
    }

    public function setBudget($budget)
    {
        $this->__load();
        return parent::setBudget($budget);
    }

    public function getBudget()
    {
        $this->__load();
        return parent::getBudget();
    }

    public function setEvaluationPoints($evaluationPoints)
    {
        $this->__load();
        return parent::setEvaluationPoints($evaluationPoints);
    }

    public function getEvaluationPoints()
    {
        $this->__load();
        return parent::getEvaluationPoints();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function __call($name, $args)
    {
        $this->__load();
        return parent::__call($name, $args);
    }

    public function &__get($name)
    {
        $this->__load();
        return parent::__get($name);
    }

    public function __set($name, $value)
    {
        $this->__load();
        return parent::__set($name, $value);
    }

    public function __isset($name)
    {
        $this->__load();
        return parent::__isset($name);
    }

    public function __unset($name)
    {
        $this->__load();
        return parent::__unset($name);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dateStart', 'dateEnd', 'isFinished', 'evaluationPoints', 'budget', 'session', 'scenario', 'scenarioSteps');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}